theme: jekyll-theme-minimal
title: ğŸ‘©ğŸ»â€ğŸ”¬>ğŸ‘©ğŸ»â€ğŸ’»>ğŸ™‹ğŸ»â€â™€ï¸
logo: /assets/img/profile_picture_small.jpeg
description: Hello! I am a Python developer, peeking into other areas of backend development. I am curious and determined, and find my way through complex scenarios.
