theme: jekyll-theme-minimal
title: ğŸ‘©ğŸ»â€ğŸ”¬>ğŸ‘©ğŸ»â€ğŸ’»>ğŸ™‹ğŸ»â€â™€ï¸âœ¨
logo: /assets/img/profile_picture_small.jpeg
description: Hello! Self-trained developer, physics-educated woman looking for new challenges. I am curious and determined, and find my way through complex scenarios. Prone to abstraction and finding patterns, I consider all dimensions of a problem.
