theme: jekyll-theme-minimal
title: ğŸ‘©ğŸ»â€ğŸ”¬>ğŸ‘©ğŸ»â€ğŸ’»>ğŸ™‹ğŸ»â€â™€ï¸
description: ã€°ï¸ my nonlinear path ã€°ï¸
email: xxx@gmail.com
author:
  name   : "name of the author"
  avatar : "/assets/profile_picture.jpeg"
