theme: jekyll-theme-minimal
title: ğŸ‘©ğŸ»â€ğŸ”¬>ğŸ‘©ğŸ»â€ğŸ’»>ğŸ™‹ğŸ»â€â™€ï¸âœ¨
logo: /assets/img/profile_picture_small.jpeg
description: Self-trained physics-educated coder, on a nonlinear journey. I am curious and determined, and find my way through complex scenarios. Prone to abstraction, finding patterns, multidimensionality.
